---
galaxy_info:
  role_name: sonarqube
  author: your_name
  description: Install and configure SonarQube
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["8", "9"]
    - name: Ubuntu
      versions: ["20.04", "22.04", "24.04"]
dependencies: []
