                                                                                    
---
- name: Install systemd unit
  ansible.builtin.template:
    src: "sonarqube.service.j2"
    dest: "/etc/systemd/system/{{ sonarqube_service_name }}.service"
    mode: "0644"
  notify:
    - daemon reload
    - restart sonarqube

- name: Enable and start service
  ansible.builtin.service:
    name: "{{ sonarqube_service_name }}"
    enabled: true
    state: started

